/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated from chart/maps/world.json and chart/maps/us.json. DO NOT EDIT.

package maps

var countryByCode = map[string]string{
	"ad": "Andorra",
	"ae": "United Arab Emirates",
	"af": "Afghanistan",
	"ag": "Antigua and Barb.",
	"al": "Albania",
	"am": "Armenia",
	"ao": "Angola",
	"ar": "Argentina",
	"as": "American Samoa",
	"at": "Austria",
	"au": "Australia",
	"ax": "Aland",
	"az": "Azerbaijan",
	"ba": "Bosnia and Herz.",
	"bb": "Barbados",
	"bd": "Bangladesh",
	"be": "Belgium",
	"bf": "Burkina Faso",
	"bg": "Bulgaria",
	"bh": "Bahrain",
	"bi": "Burundi",
	"bj": "Benin",
	"bm": "Bermuda",
	"bn": "Brunei",
	"bo": "Bolivia",
	"br": "Brazil",
	"bs": "Bahamas",
	"bt": "Bhutan",
	"bw": "Botswana",
	"by": "Belarus",
	"bz": "Belize",
	"ca": "Canada",
	"cd": "Dem. Rep. Congo",
	"cf": "Central African Rep.",
	"cg": "Congo",
	"ch": "Switzerland",
	"ci": "C\u00f4te d'Ivoire",
	"cl": "Chile",
	"cm": "Cameroon",
	"cn": "China",
	"co": "Colombia",
	"cr": "Costa Rica",
	"cu": "Cuba",
	"cv": "Cape Verde",
	"cw": "Cura\u00e7ao",
	"cy": "Cyprus",
	"cz": "Czech Rep.",
	"de": "Germany",
	"dj": "Djibouti",
	"dk": "Denmark",
	"dm": "Dominica",
	"do": "Dominican Rep.",
	"dz": "Algeria",
	"ec": "Ecuador",
	"ee": "Estonia",
	"eg": "Egypt",
	"eh": "W. Sahara",
	"er": "Eritrea",
	"es": "Spain",
	"et": "Ethiopia",
	"fi": "Finland",
	"fj": "Fiji",
	"fk": "Falkland Is.",
	"fm": "Micronesia",
	"fo": "Faeroe Is.",
	"fr": "France",
	"ga": "Gabon",
	"gb": "United Kingdom",
	"gd": "Grenada",
	"ge": "Georgia",
	"gh": "Ghana",
	"gl": "Greenland",
	"gm": "Gambia",
	"gn": "Guinea",
	"gq": "Eq. Guinea",
	"gr": "Greece",
	"gs": "S. Geo. and S. Sandw. Is.",
	"gt": "Guatemala",
	"gu": "Guam",
	"gw": "Guinea-Bissau",
	"gy": "Guyana",
	"hm": "Heard I. and McDonald Is.",
	"hn": "Honduras",
	"hr": "Croatia",
	"ht": "Haiti",
	"hu": "Hungary",
	"id": "Indonesia",
	"ie": "Ireland",
	"il": "Israel",
	"im": "Isle of Man",
	"in": "India",
	"io": "Br. Indian Ocean Ter.",
	"iq": "Iraq",
	"ir": "Iran",
	"is": "Iceland",
	"it": "Italy",
	"je": "Jersey",
	"jm": "Jamaica",
	"jo": "Jordan",
	"jp": "Japan",
	"ke": "Kenya",
	"kg": "Kyrgyzstan",
	"kh": "Cambodia",
	"ki": "Kiribati",
	"km": "Comoros",
	"kp": "Dem. Rep. Korea",
	"kr": "Korea",
	"kw": "Kuwait",
	"ky": "Cayman Is.",
	"kz": "Kazakhstan",
	"la": "Lao PDR",
	"lb": "Lebanon",
	"lc": "Saint Lucia",
	"li": "Liechtenstein",
	"lk": "Sri Lanka",
	"lr": "Liberia",
	"ls": "Lesotho",
	"lt": "Lithuania",
	"lu": "Luxembourg",
	"lv": "Latvia",
	"ly": "Libya",
	"ma": "Morocco",
	"md": "Moldova",
	"me": "Montenegro",
	"mg": "Madagascar",
	"mk": "Macedonia",
	"ml": "Mali",
	"mm": "Myanmar",
	"mn": "Mongolia",
	"mp": "N. Mariana Is.",
	"mr": "Mauritania",
	"ms": "Montserrat",
	"mt": "Malta",
	"mu": "Mauritius",
	"mw": "Malawi",
	"mx": "Mexico",
	"my": "Malaysia",
	"mz": "Mozambique",
	"na": "Namibia",
	"nc": "New Caledonia",
	"ne": "Niger",
	"ng": "Nigeria",
	"ni": "Nicaragua",
	"nl": "Netherlands",
	"no": "Norway",
	"np": "Nepal",
	"nu": "Niue",
	"nz": "New Zealand",
	"om": "Oman",
	"pa": "Panama",
	"pe": "Peru",
	"pf": "Fr. Polynesia",
	"pg": "Papua New Guinea",
	"ph": "Philippines",
	"pk": "Pakistan",
	"pl": "Poland",
	"pm": "St. Pierre and Miquelon",
	"pr": "Puerto Rico",
	"ps": "Palestine",
	"pt": "Portugal",
	"pw": "Palau",
	"py": "Paraguay",
	"qa": "Qatar",
	"ro": "Romania",
	"rs": "Serbia",
	"ru": "Russia",
	"rw": "Rwanda",
	"sa": "Saudi Arabia",
	"sb": "Solomon Is.",
	"sc": "Seychelles",
	"sd": "Sudan",
	"se": "Sweden",
	"sg": "Singapore",
	"sh": "Saint Helena",
	"si": "Slovenia",
	"sk": "Slovakia",
	"sl": "Sierra Leone",
	"sn": "Senegal",
	"so": "Somalia",
	"sr": "Suriname",
	"ss": "S. Sudan",
	"st": "S\u00e3o Tom\u00e9 and Principe",
	"sv": "El Salvador",
	"sy": "Syria",
	"sz": "Swaziland",
	"tc": "Turks and Caicos Is.",
	"td": "Chad",
	"tf": "Fr. S. Antarctic Lands",
	"tg": "Togo",
	"th": "Thailand",
	"tj": "Tajikistan",
	"tl": "Timor-Leste",
	"tm": "Turkmenistan",
	"tn": "Tunisia",
	"to": "Tonga",
	"tr": "Turkey",
	"tt": "Trinidad and Tobago",
	"tz": "Tanzania",
	"ua": "Ukraine",
	"ug": "Uganda",
	"us": "United States",
	"uy": "Uruguay",
	"uz": "Uzbekistan",
	"vc": "St. Vin. and Gren.",
	"ve": "Venezuela",
	"vi": "U.S. Virgin Is.",
	"vn": "Vietnam",
	"vu": "Vanuatu",
	"ws": "Samoa",
	"xn": "N. Cyprus",
	"xs": "Siachen Glacier",
	"ye": "Yemen",
	"za": "South Africa",
	"zm": "Zambia",
	"zw": "Zimbabwe",
}

var usStateByCode = map[string]string{
	"ak": "Alaska",
	"al": "Alabama",
	"ar": "Arkansas",
	"az": "Arizona",
	"ca": "California",
	"co": "Colorado",
	"ct": "Connecticut",
	"dc": "District of Columbia",
	"de": "Delaware",
	"fl": "Florida",
	"ga": "Georgia",
	"hi": "Hawaii",
	"ia": "Iowa",
	"id": "Idaho",
	"il": "Illinois",
	"in": "Indiana",
	"ks": "Kansas",
	"ky": "Kentucky",
	"la": "Louisiana",
	"ma": "Massachusetts",
	"md": "Maryland",
	"me": "Maine",
	"mi": "Michigan",
	"mn": "Minnesota",
	"mo": "Missouri",
	"ms": "Mississippi",
	"mt": "Montana",
	"nc": "North Carolina",
	"nd": "North Dakota",
	"ne": "Nebraska",
	"nh": "New Hampshire",
	"nj": "New Jersey",
	"nm": "New Mexico",
	"nv": "Nevada",
	"ny": "New York",
	"oh": "Ohio",
	"ok": "Oklahoma",
	"or": "Oregon",
	"pa": "Pennsylvania",
	"pr": "Puerto Rico",
	"ri": "Rhode Island",
	"sc": "South Carolina",
	"sd": "South Dakota",
	"tn": "Tennessee",
	"tx": "Texas",
	"ut": "Utah",
	"va": "Virginia",
	"vt": "Vermont",
	"wa": "Washington",
	"wi": "Wisconsin",
	"wv": "West Virginia",
	"wy": "Wyoming",
}
